
    const monsters =[
        {
            id: 1,
            name: "Parveen",
            email: "parveen12@gmail.com"
        },
        {
            id: 2,
            name: "Rahul",
            email: "rahul12@gmail.com"
        },  {
            id: 3,
            name: "Sager",
            email: "sager12@gmail.com"
        },  {
            id: 4,
            name: "Vikas",
            email: "vikas12@gmail.com"
        },  {
            id: 5,
            name: "Ankit",
            email: "ankit12@gmail.com"
        },  {
            id: 6,
            name: "Anil",
            email: "anil12@gmail.com"
        },  {
            id: 7,
            name: "Aman",
            email: "aman12@gmail.com"
        },  {
            id: 8,
            name: "Aashish",
            email: "aashish12@gmail.com"
        },  {
            id: 9,
            name: "Anu",
            email: "anu12@gmail.com"
        },  {
            id: 10,
            name: "Ajay",
            email: "ajay12@gmail.com"
        },  {
            id: 11,
            name: "Aman",
            email: "aman112@gmail.com"
        },  {
            id: 12,
            name: "Bitu",
            email: "bitu12@gmail.com"
        },  {
            id: 13,
            name: "Balbir",
            email: "balbir12@gmail.com"
        },  {
            id: 14,
            name: "Binod",
            email: "binod12@gmail.com"
        },  {
            id: 15,
            name: "Bharat",
            email: "bharat12@gmail.com"
        },  {
            id: 16,
            name: "Chetan",
            email: "chetan12@gmail.com"
        },  {
            id: 17,
            name: "Chaaya",
            email: "chaaya12@gmail.com"
        },  {
            id: 18,
            name: "Charu",
            email: "charu12@gmail.com"
        },  {
            id: 19,
            name: "Chetana",
            email: "chetana12@gmail.com"
        },  {
            id: 20,
            name: "Dinesh",
            email: "dinesh12@gmail.com"
        },  {
            id: 21,
            name: "Daaruk",
            email: "daaruk12@gmail.com"
        },  {
            id: 22,
            name: "Daamini",
            email: "daamini12@gmail.com"
        },  {
            id: 23,
            name: "Eshaan",
            email: "eshaan12@gmail.com"
        },  {
            id: 24,
            name: "Eashwari",
            email: "eashwari12@gmail.com"
        },  {
            id: 25,
            name: "Gagan",
            email: "gagan12@gmail.com"
        },  {
            id: 26,
            name: "Govind",
            email: "govind12@gmail.com"
        },  {
            id: 27,
            name: "Harsh",
            email: "harsh12@gmail.com"
        },  {
            id: 28,
            name: "Harshita",
            email: "harshita12@gmail.com"
        },  {
            id: 29,
            name: "Haridas",
            email: "haridas12@gmail.com"
        },  {
            id: 30,
            name: "Hina",
            email: "hina12@gmail.com"
        },  {
            id: 31,
            name: "Isha",
            email: "isha12@gmail.com"
        },  {
            id: 32,
            name: "Kaliyani",
            email: "kaliyani12@gmail.com"
        },  {
            id: 33,
            name: "Kapil",
            email: "kapil112@gmail.com"
        },  {
            id: 34,
            name: "Karan",
            email: "karan12@gmail.com"
        },  {
            id: 35,
            name: "Kajal",
            email: "kajal12@gmail.com"
        },  {
            id: 36,
            name: "Kanika",
            email: "kanika12@gmail.com"
        },  {
            id: 37,
            name: "Kalyani",
            email: "kalyani12@gmail.com"
        },  {
            id: 38,
            name: "Lakshya",
            email: "lakshya12@gmail.com"
        },  {
            id: 39,
            name: "Lovish",
            email: "lovish12@gmail.com"
        },  {
            id: 40,
            name: "Lovepreet",
            email: "lovepreet12@gmail.com"
        },  {
            id: 41,
            name: "Lalita",
            email: "lalita12@gmail.com"
        },  {
            id: 42,
            name: "Madhav",
            email: "madhav12@gmail.com"
        },  {
            id: 43,
            name: "Mohit",
            email: "mohit12@gmail.com"
        },  {
            id: 44,
            name: "Mukul",
            email: "mukul12@gmail.com"
        },  {
            id: 45,
            name: "Mahi",
            email: "mahi12@gmail.com"
        },  {
            id: 46,
            name: "Mohan",
            email: "mohan12@gmail.com"
        },  {
            id: 47,
            name: "Mohini",
            email: "mohini12@gmail.com"
        },  {
            id: 48,
            name: "Nitish",
            email: "nitish12@gmail.com"
        },  {
            id: 49,
            name: "Nisha",
            email: "nisha12@gmail.com"
        },  {
            id: 50,
            name: "Navay",
            email: "navya12@gmail.com"
        }
        
    ]
    export { monsters };